"""schema iniziale

Revision ID: f7ed3b5853f8
Revises: 
Create Date: 2026-07-06 12:08:14.965341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ed3b5853f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('cost_relevant', sa.Boolean(), nullable=True),
    sa.Column('cost_relevant_type', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('acquisition_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('asset_category', sa.String(length=40), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('piva', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type')
    )
    op.create_table('operating_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('company_code', sa.String(length=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('piva', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fiscal_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('source_module', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_by_id', sa.Integer(), nullable=True),
    sa.Column('reverses_id', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_by_entry_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['paid_by_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['reverses_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_number')
    )
    op.create_table('warehouse_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area_type', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['operating_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_site_sloc_code')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('dare', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avere', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_lines')
    op.drop_table('warehouse_areas')
    op.drop_table('journal_entries')
    op.drop_table('fiscal_parameters')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('operating_sites')
    op.drop_table('document_sequences')
    op.drop_table('customers')
    op.drop_table('cost_centers')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
